window.__KISHORE_ADMIN_LOADED = true;
(function () {
  'use strict';
  var cfg = window.KS_CONFIG || {}, supabase = null;
  var supabaseReady = !!(cfg.supabaseUrl && cfg.supabaseAnonKey && !String(cfg.supabaseAnonKey).includes('PASTE_'));
  var cloudinaryReady = !!(cfg.cloudinaryCloudName && cfg.cloudinaryUploadPreset && !String(cfg.cloudinaryUploadPreset).includes('PASTE_'));
  function byId(id){ return document.getElementById(id); }
  function msg(el,text,type){ if(!el)return; el.textContent=text||''; el.className='form-message'+(type?' '+type:''); }
  function esc(v){ return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c];}); }
  function showDashboard(session){ var l=byId('loginView'),d=byId('dashboardView'); if(l){l.hidden=true;l.style.display='none';} if(d){d.hidden=false;d.style.display='block';} if(byId('adminEmail'))byId('adminEmail').textContent=session&&session.user?session.user.email||'':''; loadGallery(); }
  function showLogin(){ var l=byId('loginView'),d=byId('dashboardView'); if(d){d.hidden=true;d.style.display='none';} if(l){l.hidden=false;l.style.display='';} }
  function renderFiles(){ var i=byId('mediaFiles'),o=byId('fileSummary'); if(!i||!o)return; var fs=Array.prototype.slice.call(i.files||[]),total=fs.reduce(function(n,f){return n+f.size;},0),u=['B','KB','MB','GB']; if(!total){o.textContent='No files selected';return;} var x=Math.floor(Math.log(total)/Math.log(1024)); o.textContent=fs.length+' file'+(fs.length>1?'s':'')+' selected • '+(total/Math.pow(1024,x)).toFixed(x?1:0)+' '+u[x]; }
  async function init(){
    if(!supabaseReady){msg(byId('loginMessage'),'Supabase configuration is missing.','error');return;}
    if(!window.supabase||typeof window.supabase.createClient!=='function'){msg(byId('loginMessage'),'Authentication library could not be loaded. Please refresh once.','error');return;}
    try{
      supabase=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
      var r=await supabase.auth.getSession(); if(r.error)throw r.error; if(r.data&&r.data.session)showDashboard(r.data.session);
      supabase.auth.onAuthStateChange(function(_,session){if(session)showDashboard(session);else showLogin();});
      var s=byId('connectionStatus'); if(s){s.textContent=cloudinaryReady?'Connected':'Cloudinary config needed';s.classList.toggle('ready',cloudinaryReady);}
    }catch(e){msg(byId('loginMessage'),e.message||'Could not connect to authentication service.','error');}
  }
  function bindLogin(){ var f=byId('loginForm'); if(!f)return; f.addEventListener('submit',async function(e){e.preventDefault();e.stopPropagation();var email=byId('email')?byId('email').value.trim():'',pass=byId('password')?byId('password').value:'',b=f.querySelector('button[type="submit"]'); if(!email||!pass)return msg(byId('loginMessage'),'Please enter your email and password.','error'); if(!supabase)return msg(byId('loginMessage'),'Authentication service is not available. Please refresh.','error'); if(b){b.disabled=true;b.textContent='Signing in…';} msg(byId('loginMessage'),'Connecting to secure sign-in…'); try{var r=await supabase.auth.signInWithPassword({email:email,password:pass});if(r.error)throw r.error;if(!r.data||!r.data.session)throw new Error('Sign-in completed but no session was returned.');showDashboard(r.data.session);msg(byId('loginMessage'),'Signed in successfully.','success');}catch(e){console.error('Sign-in error:',e);msg(byId('loginMessage'),'Sign-in failed: '+(e.message||'Please check your email and password.'),'error');}finally{if(b){b.disabled=false;b.textContent='Sign in';}}}); }
  async function uploadToCloudinary(file){
    if(!cloudinaryReady)throw new Error('Cloudinary configuration is incomplete.');
    var endpoint='https://api.cloudinary.com/v1_1/'+encodeURIComponent(cfg.cloudinaryCloudName)+'/auto/upload',body=new FormData(); body.append('file',file); body.append('upload_preset',cfg.cloudinaryUploadPreset);
    var response; try{response=await fetch(endpoint,{method:'POST',body:body});}catch(e){throw new Error('Could not reach Cloudinary. Check the internet connection or Cloudinary upload preset.');}
    var result={}; try{result=await response.json();}catch(_){ }
    if(!response.ok)throw new Error('Cloudinary upload failed: '+((result.error&&result.error.message)||('HTTP '+response.status))+'. Make sure kishore_gallery is an UNSIGNED upload preset.');
    if(!result.secure_url||!result.public_id)throw new Error('Cloudinary returned no media URL. Check the upload preset configuration.');
    return result;
  }
  function bindUpload(){ var f=byId('uploadForm'),input=byId('mediaFiles'); if(!f)return; if(input)input.addEventListener('change',renderFiles); f.addEventListener('submit',async function(e){e.preventDefault();var files=input?Array.prototype.slice.call(input.files||[]):[],m=byId('uploadMessage'),b=byId('uploadBtn');if(!files.length)return msg(m,'Please select at least one file.','error');if(!supabase)return msg(m,'Supabase is not connected. Refresh and sign in again.','error');if(!cloudinaryReady)return msg(m,'Cloudinary configuration is incomplete.','error');var sr=await supabase.auth.getSession();if(!sr.data||!sr.data.session)return msg(m,'Your admin session expired. Please sign in again.','error');var title=byId('title')?byId('title').value.trim():'Kishore Studios',category=byId('category')?byId('category').value:'Portraits',p=byId('uploadProgress'),bar=byId('progressBar'),pt=byId('progressText');if(b)b.disabled=true;if(p)p.hidden=false;try{for(var i=0;i<files.length;i++){var file=files[i];if(file.size>100*1024*1024)throw new Error(file.name+' is larger than 100 MB.');if(pt)pt.textContent='Uploading '+(i+1)+' of '+files.length+': '+file.name;var result=await uploadToCloudinary(file);var ins=await supabase.from('gallery').insert({public_id:result.public_id,secure_url:result.secure_url,resource_type:result.resource_type||(file.type.indexOf('video/')===0?'video':'image'),title:title,category:category});if(ins.error)throw new Error('Cloudinary upload succeeded for '+file.name+', but saving to Supabase failed: '+ins.error.message+'. If this mentions RLS/policy, run SUPABASE_SETUP.sql once in Supabase SQL Editor.');if(bar)bar.style.width=Math.round((i+1)/files.length*100)+'%';}msg(m,files.length+' item'+(files.length>1?'s':'')+' added to the public gallery.','success');f.reset();renderFiles();await loadGallery();}catch(e){console.error('Upload error:',e);msg(m,e.message||'Upload failed.','error');}finally{if(b)b.disabled=false;if(p)p.hidden=true;}}); }
  async function loadGallery(){var g=byId('adminGallery');if(!supabase||!g)return;g.innerHTML='<p class="empty-state">Loading gallery…</p>';try{var r=await supabase.from('gallery').select('*').order('created_at',{ascending:false});if(r.error)throw r.error;var d=r.data||[];if(byId('galleryCount'))byId('galleryCount').textContent=d.length+' item'+(d.length===1?'':'s');if(!d.length){g.innerHTML='<p class="empty-state">No uploads yet. Your first upload will appear here.</p>';return;}g.innerHTML=d.map(function(item){var media=item.resource_type==='video'?'<video src="'+esc(item.secure_url)+'" muted playsinline preload="metadata"></video>':'<img src="'+esc(item.secure_url)+'" alt="'+esc(item.title||'Kishore Studios photo')+'" loading="lazy">';return '<article class="admin-card"><div class="admin-media">'+media+'<span>'+esc(item.category||'Gallery')+'</span></div><div class="admin-card-body"><div><strong>'+esc(item.title||'Untitled')+'</strong><small>'+esc(item.public_id||'')+'</small></div><button class="delete-btn" data-id="'+esc(item.id)+'" type="button">Remove</button></div></article>';}).join('');}catch(e){g.innerHTML='<p class="empty-state error">'+esc(e.message||'Could not load gallery.')+'</p>';}}
  function bindDelete(){var g=byId('adminGallery');if(!g)return;g.addEventListener('click',async function(e){var b=e.target.closest?e.target.closest('.delete-btn'):null;if(!b||!supabase||!window.confirm('Remove this item from the public gallery?'))return;b.disabled=true;var r=await supabase.from('gallery').delete().eq('id',b.getAttribute('data-id'));if(r.error)window.alert(r.error.message||'Delete failed.');else loadGallery();b.disabled=false;});}
  bindLogin();bindUpload();bindDelete();var logout=byId('logoutBtn');if(logout)logout.addEventListener('click',function(){if(supabase)supabase.auth.signOut().finally(showLogin);else showLogin();});init();
})();